from dejavu import Dejavu
from dejavu.recognize import FileRecognizer, MicrophoneRecognizer
from Tkinter import *
from PIL import ImageTk
import warnings
import time
warnings.filterwarnings("ignore")

root = Tk()

root.title('Name that Song!')
root.geometry('500x800')

config = {
        "database": {
                "host": "127.0.0.1",
                "user": "root",
                "passwd": "tamotsu",
                "db": "dejavu",
                }
}


def pause():
    time.sleep(5)


def start(event):

    if __name__ == '__main__':
        djv = Dejavu(config)
        secs = 8

    song = djv.recognize(MicrophoneRecognizer, seconds=secs)
    if song is None:
        errorlabel = Label(frm2, text="Did you play the song out loud so your mic could hear it?")
        errorlabel.pack(side=TOP)
    else:
        print "From mic with %d seconds we recognized: %s\n" % (secs, song)

    if song["song_id"] == 1:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Stressed Out - Twenty One Pilots')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text='Closer - The Chainsmokers')
        recommend2.pack(side=TOP)
    if song["song_id"] == 2:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Mama Said - Lukas Graham')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text='See You Again - Wiz Khalifa ft. Charlie Puth')
        recommend2.pack(side=TOP)
        if start(event):
            frm2.pack_forget()
            start(event)
    if song["song_id"] == 3:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Just Life Fire - P!nk')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text='Hello - Adele')
        recommend2.pack(side=TOP)
    if song["song_id"] == 5:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Dangerous Woman - Ariana Grande')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Ninki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 6:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Into You - Ariana Grande')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Dangerous Woman - Ariana Grande")
        recommend2.pack(side=TOP)
    if song["song_id"] == 7:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='My Humps - The Black Eyed Peas')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Fergalicious - Fergie")
        recommend2.pack(side=TOP)
    if song["song_id"] == 8:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Uptown Funk - Mark Ronson ft. Bruno Mars')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Ride - Twenty One Pilots")
        recommend2.pack(side=TOP)
    if song["song_id"] == 9:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Closer - The Chainsmokers')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Ride - Twenty One Pilots")
        recommend2.pack(side=TOP)
    if song["song_id"] == 10:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='When I Was Your Man - Bruno Mars')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="It Will Rain - Bruno Mars")
        recommend2.pack(side=TOP)
    if song["song_id"] == 11:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='How Deep - Calvin Harris & Disciples')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Stitches - Shawn Mendes")
        recommend2.pack(side=TOP)
    if song["song_id"] == 12:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Broccoli - D.R.A.M ft. Lil Yachty')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Do You Mind - DJ Khaled ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 13:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='The Greatest - Sia')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Titanium - David Guetta ft. Sia")
        recommend2.pack(side=TOP)
    if song["song_id"] == 14:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Paradise - Coldplay')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Send My Love (To Your New Lover) - Adele")
        recommend2.pack(side=TOP)
    if song["song_id"] == 15:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Juju On That Beat - Zay Hilfigerrr & Zayion McCall')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Don't Mind - Kent Jones")
        recommend2.pack(side=TOP)
    if song["song_id"] == 16:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Hide Away - Daya")
        recommend2.pack(side=TOP)
    if song["song_id"] == 17:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='2 Phones - Kevin Gates')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Timmy Turner - Desiigner")
        recommend2.pack(side=TOP)
    if song["song_id"] == 18:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Broccoli - D.R.A.M')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Panda - Desiigner")
        recommend2.pack(side=TOP)
    if song["song_id"] == 19:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Side To Side - Ariana Grande ft. Nicki Minaj')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="No Limit - Usher ft. Young Thug")
        recommend2.pack(side=TOP)
    if song["song_id"] == 20:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Hold You Down - DJ Khaled ft. Chris Brown')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Tru - Lloyd")
        recommend2.pack(side=TOP)
    if song["song_id"] == 21:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Let Me Love You - DJ Snake ft. Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Lean On - DJ Snake & Major Lazer")
        recommend2.pack(side=TOP)
    if song["song_id"] == 22:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="In The Name Of Love - Martin Garrix & Bebe Rexha")
        recommend2.pack(side=TOP)
    if song["song_id"] == 23:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Toothbrush - DNCE')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Body Moves - DNCE")
        recommend2.pack(side=TOP)
    if song["song_id"] == 24:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 25:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Don't Wanna Know - Maroon 5")
        recommend2.pack(side=TOP)
    if song["song_id"] == 26:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='One Dance - Drake')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Don't Mind - Kent Jones")
        recommend2.pack(side=TOP)
    if song["song_id"] == 27:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Lego House - Ed Sheeran')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Stitches - Shawn Mendes")
        recommend2.pack(side=TOP)
    if song["song_id"] == 28:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text="I'm Not The Only One - Sam Smith")
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 29:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text="Don't Let Me Down - The Chainsmokers")
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Lights - Ellie Goulding")
        recommend2.pack(side=TOP)
    if song["song_id"] == 30:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Going Under - Evanescence')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Sweet Sacrifice - Evanescence")
        recommend2.pack(side=TOP)
    if song["song_id"] == 31:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Hold Up - Beyonce')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 32:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Sorry - Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 33:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='BO$$ - Fifth Harmony')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Sorry - Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 34:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="You've Got The Love - Florence And The Machine")
        recommend2.pack(side=TOP)
    if song["song_id"] == 35:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Don't Wanna Know - Maroon 5")
        recommend2.pack(side=TOP)
    if song["song_id"] == 36:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Just Give Me A Reason - P!nk ft. Nate Ruess')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Royals - Lorde")
        recommend2.pack(side=TOP)
    if song["song_id"] == 37:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="What They Want - Russs")
        recommend2.pack(side=TOP)
    if song["song_id"] == 38:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='I Took A Pill In Ibiza - Mike Posner')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack(side=TOP)
    if song["song_id"] == 39:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='What The Hell - Avril Lavigne')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Demons - Imagine Dragons")
        recommend2.pack(side=TOP)
    if song["song_id"] == 40:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Waiting On The World To Change - John Mayer')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Daughters - John Mayer")
        recommend2.pack(side=TOP)
    if song["song_id"] == 41:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Hotling Bling - Drake')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Uptown Funk - Mark Ronson ft. Bruno Mars")
        recommend2.pack(side=TOP)
    if song["song_id"] == 42:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='This Is What You Came For - Calvin Harris')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Faded - Alan Walker")
        recommend2.pack(side=TOP)
    if song["song_id"] == 43:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Treat You Better - Shawn Mendes')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Don't Let Me Down - The Chainsmokers")
        recommend2.pack(side=TOP)
    if song["song_id"] == 44:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Counting Stars - OneRepublic')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Take Me To Church - Hozier")
        recommend2.pack(side=TOP)
    if song["song_id"] == 45:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 46:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Scars To Your Beaufitul - Alessia Cara')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 47:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Locked Away - R City ft. Adam Levine')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Sorry - Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 48:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Rock On - Tucker Beathard')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Backroad Song - Granger Smith")
        recommend2.pack(side=TOP)
    if song["song_id"] == 49:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Cake By The Ocean - DNCE")
        recommend2.pack(side=TOP)
    if song["song_id"] == 50:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Cry Me A River - Justin Timberlake')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Not A Bad Thing - Justin Timberlake")
        recommend2.pack(side=TOP)
    if song["song_id"] == 51:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Hot N Cold - Katy Perry')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 52:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Side To Side - Ariana Grande ft. Nicki Minaj')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 53:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='I Took A Pill In Ibiza - Mike Posner')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Don't Wanna Know - Maroon 5")
        recommend2.pack(side=TOP)
    if song["song_id"] == 54:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='The Greatest - Sia')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Million Reasons - Lady Gaga")
        recommend2.pack(side=TOP)
    if song["song_id"] == 55:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Bartender - Lady Antebellum')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="What Hurts The Most - Rascal Flatts")
        recommend2.pack(side=TOP)
    if song["song_id"] == 56:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Starry Eyed - Ellie Goulding')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Anything Could - Ellie Goulding")
        recommend2.pack(side=TOP)
    if song["song_id"] == 57:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Criminal Mind - Lukas Graham')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack(side=TOP)
    if song["song_id"] == 58:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Let Me Love You - DJ Snake ft. Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack(side=TOP)
    if song["song_id"] == 59:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='24K Magic - Bruno Mars')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Blank Space - Taylor Swift")
        recommend2.pack(side=TOP)
    if song["song_id"] == 60:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Treat You Better - Shawn Mendes')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Don't Wanna Know - Maroon 5")
        recommend2.pack(side=TOP)
    if song["song_id"] == 61:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Marvin Gaye - Charlie Puth ft. Meghan Trainor')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack(side=TOP)
    if song["song_id"] == 62:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Blank Space - Taylor Swift')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="All About That Bass - Meghan Trainor")
        recommend2.pack(side=TOP)
    if song["song_id"] == 63:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Summer - Calvin Harris')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 64:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Locked Away - R City ft. Adam Levine')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack(side=TOP)
    if song["song_id"] == 65:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 66:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='So What - P!nk')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Love The Way You Lie - Eminem ft. Rihanna")
        recommend2.pack(side=TOP)
    if song["song_id"] == 67:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 68:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Shake It Off - Taylor Swift')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Let Me Love You - DJ Snake ft. Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 69:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Die Young - Ke$ha')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Counting Stars - OneRepublic")
        recommend2.pack(side=TOP)
    if song["song_id"] == 70:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Kiss It Better - Rihanna')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Pour It Up - Rihanna")
        recommend2.pack(side=TOP)
    if song["song_id"] == 71:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Love Song - Adele')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Diamonds - Rihanna")
        recommend2.pack(side=TOP)
    if song["song_id"] == 72:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Titanium - David Guetta')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Blank Space - Taylor Swift")
        recommend2.pack(side=TOP)
    if song["song_id"] == 73:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Kiss It Better - Rihanna')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="One Dance - Drake")
        recommend2.pack(side=TOP)
    if song["song_id"] == 74:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Let Her Go - Passenger')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Counting Stars - One Republic")
        recommend2.pack(side=TOP)
    if song["song_id"] == 75:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Hello - Adele')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Skyfall - Adele")
        recommend2.pack(side=TOP)
    if song["song_id"] == 76:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Mercy - Shawn Mendes')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Into You - Ariana Grande")
        recommend2.pack(side=TOP)
    if song["song_id"] == 77:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Hotline Bling - Drake')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="One Call Away - Charlie Puth")
        recommend2.pack(side=TOP)
    if song["song_id"] == 78:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Hymn For The Weekend - Coldplay')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="One Dance - Drake")
        recommend2.pack(side=TOP)
    if song["song_id"] == 79:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text="Hips Don't Lie - Shakira")
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Moves Like Jagger - Maroon 5")
        recommend2.pack(side=TOP)
    if song["song_id"] == 80:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='The Greatest - Sia')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Sit Still, Look Pretty - Daya")
        recommend2.pack(side=TOP)
    if song["song_id"] == 81:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='In The Name of Love - Martin Garrix')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Big Girls Cry - Sia")
        recommend2.pack(side=TOP)
    if song["song_id"] == 82:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Drive - Incubus')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Say It Ain't So - Weezer")
        recommend2.pack(side=TOP)
    if song["song_id"] == 83:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Purple Lamborghini - Skrillex')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Starboy - The Weeked")
        recommend2.pack(side=TOP)
    if song["song_id"] == 84:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Thinking Out Loud - Ed Sheeran')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="I'm Not the Only One - Sam Smith")
        recommend2.pack(side=TOP)
    if song["song_id"] == 85:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Black Beetles - Rae Sremmond ft. Gucci Mane')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Counting Stars - One Republic")
        recommend2.pack(side=TOP)
    if song["song_id"] == 86:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Heathens - Twenty One Pilots')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Radioactive - Imagine Dragons")
        recommend2.pack(side=TOP)
    if song["song_id"] == 87:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text="We Don't Talk Anymore - Charlie Puth")
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="This Is What You Came For Lyrics - Calvin Harris ft. Rihanna")
        recommend2.pack(side=TOP)
    if song["song_id"] == 88:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Take Me To Church - Hozier')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Mirrors - Justin Timberlake")
        recommend2.pack(side=TOP)
    if song["song_id"] == 89:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Timmy Turner - Desiigner')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Treat You Better - Shawn Mendes")
        recommend2.pack(side=TOP)
    if song["song_id"] == 90:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Just The Way You Are lyrics - Bruno Mars')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Thinking out Loud - Ed Sheeran")
        recommend2.pack(side=TOP)
    if song["song_id"] == 91:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Cheap Thrills - Sia ft. Sean Paul')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Starving - Hailee Steinfeld Grey feat Zedd")
        recommend2.pack(side=TOP)
    if song["song_id"] == 92:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Heathens- Twenty One Pilots')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Adele - Send My Love (To Your New Lover)")
        recommend2.pack(side=TOP)
    if song["song_id"] == 93:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text="Don't Let Me Down- The Chainsmokers ft. Daya")
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="This Is What You Came For - Calvin Harris ft. Rihanna")
        recommend2.pack(side=TOP)
    if song["song_id"] == 94:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Young M.A - OOOUUU')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Do You Mind - DJ Khaled ft Chris Brown Nicki Minaj")
        recommend2.pack(side=TOP)
    if song["song_id"] == 95:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Meghan Trainor - Lips Are Movin')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Gnash - I hate u, I love u")
        recommend2.pack(side=TOP)
    if song["song_id"] == 96:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Justin Bieber - What Do You Mean')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Shawn Mendes - Treat You Better")
        recommend2.pack(side=TOP)
    if song["song_id"] == 97:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Love Yourself - Justin Bieber')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Let me love you -DJ Snake _ Justin Bieber")
        recommend2.pack(side=TOP)
    if song["song_id"] == 98:
        id = Label(frm2, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm2, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm2, text='Ride - Twenty One Pilots')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm2, text="Work from Home - Fifth Harmony ft. Ty Dolla $")
        recommend2.pack(side=TOP)
    if song["song_id"] == 99:
        id = Label(frm, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(frm, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(frm, text='No Problem - Chance The Rapper ft. 2 Chainz and Lil Wayne')
        recommend1.pack(side=TOP)
        recommend2 = Label(frm, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack(side=TOP)

root.grid_rowconfigure(0, weight=1)
root.grid_columnconfigure(0, weight=1)

cnv = Canvas(root, bg="white")
cnv.grid(row=0, column=0, sticky='nswe')
image = ImageTk.PhotoImage(file="/Users/markkinoshita/Desktop/CST205_Project_3-kyle/GUI images/background.gif")
cnv.create_image(250, 0, image=image, anchor=N)
hScroll = Scrollbar(root, orient=HORIZONTAL, command=cnv.xview)
#hScroll.grid(row=1, column=0, sticky='we')
#vScroll = Scrollbar(root, orient=VERTICAL, command=cnv.yview)
#vScroll.grid(row=0, column=1, sticky='ns')
#cnv.configure(xscrollcommand=hScroll.set, yscrollcommand=vScroll.set)

frm = Frame(cnv, bg="white")
frm2 = Frame(cnv, bg="white")


cnv.create_window(250, 0, window=frm, anchor='n')
cnv.create_window(250, 150, window=frm2, anchor='n')
T = Text(frm, height=6, width=45)
T.pack(side=TOP)
T.insert(END, "         Welcome to 'Name that Song!'\n   Press the button be"
              ""
              ""
              "low to get started!\n")
Listenbutton = Button(frm, text='Start listening', width=10)
Listenbutton.bind("<Button-1>", start)
Listenbutton.pack(side=TOP, padx=2, pady=2)

frm.update_idletasks()
frm2.update_idletasks()

#cnv.configure(scrollregion=(0, 0, frm2.winfo_width(), frm.winfo_height()))

root.mainloop()
