import warnings
warnings.filterwarnings("ignore")
from dejavu import Dejavu
from dejavu.recognize import FileRecognizer, MicrophoneRecognizer
from Tkinter import *
from ttk import *

root = Tk()
root.title('Name that Song!')
root.resizable(width=False, height=False)
root.geometry('600x600')
root.grid_rowconfigure(0, weight=1)
root.grid_columnconfigure(0, weight=1)
canvas = Canvas(root)
canvas.grid(row=0, column=0, sticky='nswe')
h_scroll = Scrollbar(root, orient=HORIZONTAL, command=canvas.xview)


h_scroll.grid(row=1, column=0, sticky='we')
v_scroll = Scrollbar(root, orient=VERTICAL, command=canvas.yview)
v_scroll.grid(row=0, column=1, sticky='ns')
canvas.configure(xscrollcommand=h_scroll.set, yscrollcommand=v_scroll.set)
topframe = Frame(canvas, relief=SUNKEN)
leftframe = Frame(canvas, relief=SUNKEN)
rightframe = Frame(canvas, relief=SUNKEN)
bottomframe = Frame(canvas, relief=SUNKEN)
canvas.create_window(300, 50, window=topframe, anchor='n')
canvas.create_window(50, 60, window=leftframe, anchor='nw')
canvas.create_window(1, 1, window=bottomframe, anchor='s')
canvas.create_window(50, 60, window=rightframe, anchor="nw")
topframe.update_idletasks()
leftframe.update_idletasks()
rightframe.update_idletasks()
bottomframe.update_idletasks()
canvas.configure(scrollregion=(0, 0, rightframe.winfo_width(), rightframe.winfo_height()))

config = {
        "database": {
                "host": "127.0.0.1",
                "user": "root",
                "passwd": "tamotsu",
                "db": "dejavu",
                }
}


def start(event):

    if __name__ == '__main__':

        djv = Dejavu(config)
        secs = 8

    song = djv.recognize(MicrophoneRecognizer, seconds=secs)
    if song is None:
        print "Nothing recognized -- did you play the song out loud so your mic could hear it?"
    else:
        print "From mic with %d seconds we recognized: %s\n" % (secs, song)

    if song["song_id"] == 1:
        id = Label(rightframe, text='Your song:  ' + song['song_name'])
        id.pack(side=TOP)
        recommend = Label(rightframe, text='Recommended songs:')
        recommend.pack(side=TOP)
        recommend1 = Label(rightframe, text='Stressed Out - Twenty One Pilots')
        recommend1.pack(side=TOP)
        recommend2 = Label(rightframe, text='Closer - The Chainsmokers')
        recommend2.pack(side=TOP)
    if song["song_id"] == 2:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Mama Said - Lukas Graham')
        recommend1.pack()
        recommend2 = Label(root, text='See You Again - Wiz Khalifa ft. Charlie Puth')
        recommend2.pack()
    if song["song_id"] == 3:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Just Life Fire - P!nk')
        recommend1.pack()
        recommend2 = Label(root, text='Hello - Adele')
        recommend2.pack()
    if song["song_id"] == 5:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Dangerous Woman - Ariana Grande')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Ninki Minaj")
        recommend2.pack()
    if song["song_id"] == 6:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Into You - Ariana Grande')
        recommend1.pack()
        recommend2 = Label(root, text="Dangerous Woman - Ariana Grande")
        recommend2.pack()
    if song["song_id"] == 7:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='My Humps - The Black Eyed Peas')
        recommend1.pack()
        recommend2 = Label(root, text="Fergalicious - Fergie")
        recommend2.pack()
    if song["song_id"] == 8:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Uptown Funk - Mark Ronson ft. Bruno Mars')
        recommend1.pack()
        recommend2 = Label(root, text="Ride - Twenty One Pilots")
        recommend2.pack()
    if song["song_id"] == 9:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Closer - The Chainsmokers')
        recommend1.pack()
        recommend2 = Label(root, text="Ride - Twenty One Pilots")
        recommend2.pack()
    if song["song_id"] == 10:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='When I Was Your Man - Bruno Mars')
        recommend1.pack()
        recommend2 = Label(root, text="It Will Rain - Bruno Mars")
        recommend2.pack()
    if song["song_id"] == 11:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='How Deep - Calvin Harris & Disciples')
        recommend1.pack()
        recommend2 = Label(root, text="Stitches - Shawn Mendes")
        recommend2.pack()
    if song["song_id"] == 12:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Broccoli - D.R.A.M ft. Lil Yachty')
        recommend1.pack()
        recommend2 = Label(root, text="Do You Mind - DJ Khaled ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 13:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='The Greatest - Sia')
        recommend1.pack()
        recommend2 = Label(root, text="Titanium - David Guetta ft. Sia")
        recommend2.pack()
    if song["song_id"] == 14:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Paradise - Coldplay')
        recommend1.pack()
        recommend2 = Label(root, text="Send My Love (To Your New Lover) - Adele")
        recommend2.pack()
    if song["song_id"] == 15:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Juju On That Beat - Zay Hilfigerrr & Zayion McCall')
        recommend1.pack()
        recommend2 = Label(root, text="Don't Mind - Kent Jones")
        recommend2.pack()
    if song["song_id"] == 16:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack()
        recommend2 = Label(root, text="Hide Away - Daya")
        recommend2.pack()
    if song["song_id"] == 17:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='2 Phones - Kevin Gates')
        recommend1.pack()
        recommend2 = Label(root, text="Timmy Turner - Desiigner")
        recommend2.pack()
    if song["song_id"] == 18:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Broccoli - D.R.A.M')
        recommend1.pack()
        recommend2 = Label(root, text="Panda - Desiigner")
        recommend2.pack()
    if song["song_id"] == 19:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Side To Side - Ariana Grande ft. Nicki Minaj')
        recommend1.pack()
        recommend2 = Label(root, text="No Limit - Usher ft. Young Thug")
        recommend2.pack()
    if song["song_id"] == 20:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Hold You Down - DJ Khaled ft. Chris Brown')
        recommend1.pack()
        recommend2 = Label(root, text="Tru - Lloyd")
        recommend2.pack()
    if song["song_id"] == 21:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Let Me Love You - DJ Snake ft. Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="Lean On - DJ Snake & Major Lazer")
        recommend2.pack()
    if song["song_id"] == 22:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="In The Name Of Love - Martin Garrix & Bebe Rexha")
        recommend2.pack()
    if song["song_id"] == 23:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Toothbrush - DNCE')
        recommend1.pack()
        recommend2 = Label(root, text="Body Moves - DNCE")
        recommend2.pack()
    if song["song_id"] == 24:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 25:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack()
        recommend2 = Label(root, text="Don't Wanna Know - Maroon 5")
        recommend2.pack()
    if song["song_id"] == 26:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='One Dance - Drake')
        recommend1.pack()
        recommend2 = Label(root, text="Don't Mind - Kent Jones")
        recommend2.pack()
    if song["song_id"] == 27:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Lego House - Ed Sheeran')
        recommend1.pack()
        recommend2 = Label(root, text="Stitches - Shawn Mendes")
        recommend2.pack()
    if song["song_id"] == 28:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text="I'm Not The Only One - Sam Smith")
        recommend1.pack()
        recommend2 = Label(root, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 29:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text="Don't Let Me Down - The Chainsmokers")
        recommend1.pack()
        recommend2 = Label(root, text="Lights - Ellie Goulding")
        recommend2.pack()
    if song["song_id"] == 30:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Going Under - Evanescence')
        recommend1.pack()
        recommend2 = Label(root, text="Sweet Sacrifice - Evanescence")
        recommend2.pack()
    if song["song_id"] == 31:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Hold Up - Beyonce')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 32:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Sorry - Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 33:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='BO$$ - Fifth Harmony')
        recommend1.pack()
        recommend2 = Label(root, text="Sorry - Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 34:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack()
        recommend2 = Label(root, text="You've Got The Love - Florence And The Machine")
        recommend2.pack()
    if song["song_id"] == 35:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack()
        recommend2 = Label(root, text="Don't Wanna Know - Maroon 5")
        recommend2.pack()
    if song["song_id"] == 36:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Just Give Me A Reason - P!nk ft. Nate Ruess')
        recommend1.pack()
        recommend2 = Label(root, text="Royals - Lorde")
        recommend2.pack()
    if song["song_id"] == 37:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="What They Want - Russs")
        recommend2.pack()
    if song["song_id"] == 38:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='I Took A Pill In Ibiza - Mike Posner')
        recommend1.pack()
        recommend2 = Label(root, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack()
    if song["song_id"] == 39:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='What The Hell - Avril Lavigne')
        recommend1.pack()
        recommend2 = Label(root, text="Demons - Imagine Dragons")
        recommend2.pack()
    if song["song_id"] == 40:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Waiting On The World To Change - John Mayer')
        recommend1.pack()
        recommend2 = Label(root, text="Daughters - John Mayer")
        recommend2.pack()
    if song["song_id"] == 41:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Hotling Bling - Drake')
        recommend1.pack()
        recommend2 = Label(root, text="Uptown Funk - Mark Ronson ft. Bruno Mars")
        recommend2.pack()
    if song["song_id"] == 42:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='This Is What You Came For - Calvin Harris')
        recommend1.pack()
        recommend2 = Label(root, text="Faded - Alan Walker")
        recommend2.pack()
    if song["song_id"] == 43:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Treat You Better - Shawn Mendes')
        recommend1.pack()
        recommend2 = Label(root, text="Don't Let Me Down - The Chainsmokers")
        recommend2.pack()
    if song["song_id"] == 44:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Counting Stars - OneRepublic')
        recommend1.pack()
        recommend2 = Label(root, text="Take Me To Church - Hozier")
        recommend2.pack()
    if song["song_id"] == 45:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 46:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Scars To Your Beaufitul - Alessia Cara')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 47:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Locked Away - R City ft. Adam Levine')
        recommend1.pack()
        recommend2 = Label(root, text="Sorry - Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 48:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Rock On - Tucker Beathard')
        recommend1.pack()
        recommend2 = Label(root, text="Backroad Song - Granger Smith")
        recommend2.pack()
    if song["song_id"] == 49:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="Cake By The Ocean - DNCE")
        recommend2.pack()
    if song["song_id"] == 50:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Cry Me A River - Justin Timberlake')
        recommend1.pack()
        recommend2 = Label(root, text="Not A Bad Thing - Justin Timberlake")
        recommend2.pack()
    if song["song_id"] == 51:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Hot N Cold - Katy Perry')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 52:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Side To Side - Ariana Grande ft. Nicki Minaj')
        recommend1.pack()
        recommend2 = Label(root, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 53:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='I Took A Pill In Ibiza - Mike Posner')
        recommend1.pack()
        recommend2 = Label(root, text="Don't Wanna Know - Maroon 5")
        recommend2.pack()
    if song["song_id"] == 54:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='The Greatest - Sia')
        recommend1.pack()
        recommend2 = Label(root, text="Million Reasons - Lady Gaga")
        recommend2.pack()
    if song["song_id"] == 55:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Bartender - Lady Antebellum')
        recommend1.pack()
        recommend2 = Label(root, text="What Hurts The Most - Rascal Flatts")
        recommend2.pack()
    if song["song_id"] == 56:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Starry Eyed - Ellie Goulding')
        recommend1.pack()
        recommend2 = Label(root, text="Anything Could - Ellie Goulding")
        recommend2.pack()
    if song["song_id"] == 57:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Criminal Mind - Lukas Graham')
        recommend1.pack()
        recommend2 = Label(root, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack()
    if song["song_id"] == 58:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Let Me Love You - DJ Snake ft. Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack()
    if song["song_id"] == 59:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='24K Magic - Bruno Mars')
        recommend1.pack()
        recommend2 = Label(root, text="Blank Space - Taylor Swift")
        recommend2.pack()
    if song["song_id"] == 60:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Treat You Better - Shawn Mendes')
        recommend1.pack()
        recommend2 = Label(root, text="Don't Wanna Know - Maroon 5")
        recommend2.pack()
    if song["song_id"] == 61:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Marvin Gaye - Charlie Puth ft. Meghan Trainor')
        recommend1.pack()
        recommend2 = Label(root, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack()
    if song["song_id"] == 62:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Blank Space - Taylor Swift')
        recommend1.pack()
        recommend2 = Label(root, text="All About That Bass - Meghan Trainor")
        recommend2.pack()
    if song["song_id"] == 63:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Summer - Calvin Harris')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 64:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Locked Away - R City ft. Adam Levine')
        recommend1.pack()
        recommend2 = Label(root, text="Scars To Your Beautiful - Alessia Cara")
        recommend2.pack()
    if song["song_id"] == 65:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Cold Water - Major Lazer ft. Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 66:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='So What - P!nk')
        recommend1.pack()
        recommend2 = Label(root, text="Love The Way You Lie - Eminem ft. Rihanna")
        recommend2.pack()
    if song["song_id"] == 67:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Scars To Your Beautiful - Alessia Cara')
        recommend1.pack()
        recommend2 = Label(root, text="Cold Water - Major Lazer ft. Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 68:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Shake It Off - Taylor Swift')
        recommend1.pack()
        recommend2 = Label(root, text="Let Me Love You - DJ Snake ft. Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 69:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Die Young - Ke$ha')
        recommend1.pack()
        recommend2 = Label(root, text="Counting Stars - OneRepublic")
        recommend2.pack()
    if song["song_id"] == 70:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Kiss It Better - Rihanna')
        recommend1.pack()
        recommend2 = Label(root, text="Pour It Up - Rihanna")
        recommend2.pack()
    if song["song_id"] == 71:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Love Song - Adele')
        recommend1.pack()
        recommend2 = Label(root, text="Diamonds - Rihanna")
        recommend2.pack()
    if song["song_id"] == 72:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Titanium - David Guetta')
        recommend1.pack()
        recommend2 = Label(root, text="Blank Space - Taylor Swift")
        recommend2.pack()
    if song["song_id"] == 73:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Kiss It Better - Rihanna')
        recommend1.pack()
        recommend2 = Label(root, text="One Dance - Drake")
        recommend2.pack()
    if song["song_id"] == 74:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Let Her Go - Passenger')
        recommend1.pack()
        recommend2 = Label(root, text="Counting Stars - One Republic")
        recommend2.pack()
    if song["song_id"] == 75:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Hello - Adele')
        recommend1.pack()
        recommend2 = Label(root, text="Skyfall - Adele")
        recommend2.pack()
    if song["song_id"] == 76:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Mercy - Shawn Mendes')
        recommend1.pack()
        recommend2 = Label(root, text="Into You - Ariana Grande")
        recommend2.pack()
    if song["song_id"] == 77:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Hotline Bling - Drake')
        recommend1.pack()
        recommend2 = Label(root, text="One Call Away - Charlie Puth")
        recommend2.pack()
    if song["song_id"] == 78:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Hymn For The Weekend - Coldplay')
        recommend1.pack()
        recommend2 = Label(root, text="One Dance - Drake")
        recommend2.pack()
    if song["song_id"] == 79:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text="Hips Don't Lie - Shakira")
        recommend1.pack()
        recommend2 = Label(root, text="Moves Like Jagger - Maroon 5")
        recommend2.pack()
    if song["song_id"] == 80:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='The Greatest - Sia')
        recommend1.pack()
        recommend2 = Label(root, text="Sit Still, Look Pretty - Daya")
        recommend2.pack()
    if song["song_id"] == 81:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='In The Name of Love - Martin Garrix')
        recommend1.pack()
        recommend2 = Label(root, text="Big Girls Cry - Sia")
        recommend2.pack()
    if song["song_id"] == 82:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Drive - Incubus')
        recommend1.pack()
        recommend2 = Label(root, text="Say It Ain't So - Weezer")
        recommend2.pack()
    if song["song_id"] == 83:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Purple Lamborghini - Skrillex')
        recommend1.pack()
        recommend2 = Label(root, text="Starboy - The Weeked")
        recommend2.pack()
    if song["song_id"] == 84:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Thinking Out Loud - Ed Sheeran')
        recommend1.pack()
        recommend2 = Label(root, text="I'm Not the Only One - Sam Smith")
        recommend2.pack()
    if song["song_id"] == 85:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Black Beetles - Rae Sremmond ft. Gucci Mane')
        recommend1.pack()
        recommend2 = Label(root, text="Counting Stars - One Republic")
        recommend2.pack()
    if song["song_id"] == 86:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Heathens - Twenty One Pilots')
        recommend1.pack()
        recommend2 = Label(root, text="Radioactive - Imagine Dragons")
        recommend2.pack()
    if song["song_id"] == 87:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text="We Don't Talk Anymore - Charlie Puth")
        recommend1.pack()
        recommend2 = Label(root, text="This Is What You Came For Lyrics - Calvin Harris ft. Rihanna")
        recommend2.pack()
    if song["song_id"] == 88:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Take Me To Church - Hozier')
        recommend1.pack()
        recommend2 = Label(root, text="Mirrors - Justin Timberlake")
        recommend2.pack()
    if song["song_id"] == 89:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Timmy Turner - Desiigner')
        recommend1.pack()
        recommend2 = Label(root, text="Treat You Better - Shawn Mendes")
        recommend2.pack()
    if song["song_id"] == 90:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Just The Way You Are lyrics - Bruno Mars')
        recommend1.pack()
        recommend2 = Label(root, text="Thinking out Loud - Ed Sheeran")
        recommend2.pack()
    if song["song_id"] == 91:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Cheap Thrills - Sia ft. Sean Paul')
        recommend1.pack()
        recommend2 = Label(root, text="Starving - Hailee Steinfeld Grey feat Zedd")
        recommend2.pack()
    if song["song_id"] == 92:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Heathens- Twenty One Pilots')
        recommend1.pack()
        recommend2 = Label(root, text="Adele - Send My Love (To Your New Lover)")
        recommend2.pack()
    if song["song_id"] == 93:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text="Don't Let Me Down- The Chainsmokers ft. Daya")
        recommend1.pack()
        recommend2 = Label(root, text="This Is What You Came For - Calvin Harris ft. Rihanna")
        recommend2.pack()
    if song["song_id"] == 94:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Young M.A - OOOUUU')
        recommend1.pack()
        recommend2 = Label(root, text="Do You Mind - DJ Khaled ft Chris Brown Nicki Minaj")
        recommend2.pack()
    if song["song_id"] == 95:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Meghan Trainor - Lips Are Movin')
        recommend1.pack()
        recommend2 = Label(root, text="Gnash - I hate u, I love u")
        recommend2.pack()
    if song["song_id"] == 96:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Justin Bieber - What Do You Mean')
        recommend1.pack()
        recommend2 = Label(root, text="Shawn Mendes - Treat You Better")
        recommend2.pack()
    if song["song_id"] == 97:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Love Yourself - Justin Bieber')
        recommend1.pack()
        recommend2 = Label(root, text="Let me love you -DJ Snake _ Justin Bieber")
        recommend2.pack()
    if song["song_id"] == 98:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='Ride - Twenty One Pilots')
        recommend1.pack()
        recommend2 = Label(root, text="Work from Home - Fifth Harmony ft. Ty Dolla $")
        recommend2.pack()
    if song["song_id"] == 99:
        id = Label(root, text='Your song:  ' + song['song_name'])
        id.pack()
        recommend = Label(root, text='Recommended songs:')
        recommend.pack()
        recommend1 = Label(root, text='No Problem - Chance The Rapper ft. 2 Chainz and Lil Wayne')
        recommend1.pack()
        recommend2 = Label(root, text="Side To Side - Ariana Grande ft. Nicki Minaj")
        recommend2.pack()

status = Label(bottomframe, text="Ready to listen.........", relief=SUNKEN, anchor=W)
status.pack(side=BOTTOM, fill=X)
ListenButton = Button(topframe, text="Start listening", width=40)
ListenButton.bind("<Button-1>", start)
ListenButton.pack(side=TOP)

root.mainloop()